## Creating a Basic DataFrame

In [40]:
import pandas as pd
data=[[10,20,30],
      [90,45,56],
      [12,34,56]]

df=pd.DataFrame(data, columns=["col1","col2", "col3"])
print(df)

   col1  col2  col3
0    10    20    30
1    90    45    56
2    12    34    56

In [ ]:
df.head() # shows first 5 rows

   col1  col2  col3
0    10    20    30
1    90    45    56
2    12    34    56

In [42]:
df.tail() # shows last 5 rows

   col1  col2  col3
0    10    20    30
1    90    45    56
2    12    34    56

In [59]:
df.iloc[0] # gets a row by index

col1    10
col2    20
col3    30
Name: row1, dtype: int64

In [ ]:
df["col1"].head()  #gets a column as a series

row1    10
row2    90
row3    12
Name: col1, dtype: int64

In [49]:
df.describe()

            col1       col2       col3
count   3.000000   3.000000   3.000000
mean   37.333333  33.000000  47.333333
std    45.621632  12.529964  15.011107
min    10.000000  20.000000  30.000000
25%    11.000000  27.000000  43.000000
50%    12.000000  34.000000  56.000000
75%    51.000000  39.500000  56.000000
max    90.000000  45.000000  56.000000

###  From a list of values

In [22]:
import pandas as pd
import numpy as np

In [ ]:
#1
data=(["A", "B", "C", "D"])
df = pd.DataFrame(data,columns=["   Letters"])
print(df)

     Letters
0          A
1          B
2          C
3          D

In [ ]:
#2
data=["RAM","RAJ","KOY","POP"]

df=pd.DataFrame(data, columns=["Names"])
print(df)

  Name
0  RAM
1  RAJ
2  KOY
3  POP

### Custom Index Creation

In [50]:
import pandas as pd
data=[[10,20,30],
      [90,45,56],
      [12,34,56]]

df=pd.DataFrame(data, columns=["col1","col2", "col3"],index=["row1","row2","row3"])
print(df)

      col1  col2  col3
row1    10    20    30
row2    90    45    56
row3    12    34    56

### From a dictionary of lists

In [31]:
data ={
    "Name": ["Alise","Jose","Mike","Jack"],
    "AGE":[23,56,72,65],
    "GENDER":["M","F","M","F"]
}

df= pd.DataFrame(data)
print(df)

    Name  AGE GENDER
0  Alise   23      M
1   Jose   56      F
2   Mike   72      M
3   Jack   65      F

In [36]:
data = {
    "ID": [1, "Alice", 85],
    "Name": [2, "Bob", 90],
    "Score": [3, "Charlie", 88]
}
df = pd.DataFrame(data)
print(df)

      ID Name    Score
0      1    2        3
1  Alice  Bob  Charlie
2     85   90       88

### From a list of dictionaries

In [34]:
data = [
    {"Name": "Alice", "Age": 25},
    {"Name": "Bob", "Age": 30},
    {"Name": "Charlie", "Age": 35}
]
df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

### From a list of lists (or tuples)

In [35]:
data = [
    [1, "Alice", 85],
    [2, "Bob", 90],
    [3, "Charlie", 88]
]
df = pd.DataFrame(data, columns=["ID", "Name", "Score"])
print(df)

   ID     Name  Score
0   1    Alice     85
1   2      Bob     90
2   3  Charlie     88

###  From a NumPy array

In [38]:
import numpy as np

data = np.array([[10, 20],
                  [30, 40],
                    [50, 60]])
df = pd.DataFrame(data, columns=["Col1", "Col2"])
print(df)

   Col1  Col2
0    10    20
1    30    40
2    50    60

## Loading Data

In [5]:
coffee=pd.read_csv("warmup-data/coffee.csv")
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

### Other File Formats

In [93]:
## parquet files
df=pd.read_parquet("data\\results.parquet")
df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,None,26.0,False,None
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,None,28.0,False,None
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,None
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,None,NaN,False,None
308407,2022.0,Winter,None,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,None,None,24.0,False,None

## Accessing Data with Pandas

### CSV Files

In [115]:
coffee=pd.read_csv("warmup-data/coffee.csv")

In [67]:
# View data
coffee.head(10)        # First 10 rows
coffee.tail(10)        # Last 10 rows
coffee.sample(5)       # 5 random rows
coffee.sample(5, random_state=42)  # Reproducible random sample

          Day Coffee Type  Units Sold
9      Friday       Latte          35
11   Saturday       Latte          35
0      Monday    Espresso         100
12     Sunday    Espresso          45
5   Wednesday       Latte          25

In [44]:
'''Select rows and columns by labels'''
# coffee.loc[0]                    # First row
# coffee.loc[0:2]                  # Rows 0 to 2
# coffee.loc[:5, 'Units Sold']    # All rows, specific column
coffee.loc[0:2, ["Day",'Units Sold']] # Rows 0-2, specific columns

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30

In [53]:
# Select by integer position
coffee.iloc[0]          # First row
coffee.iloc[:3]         # First 3 rows  
coffee.iloc[:, 1]       # All rows, second column
coffee.iloc[0:3, 1:3]   # Rows 0-2, columns 1-3

  Coffee Type  Units Sold
0    Espresso          25
1       Latte          15
2    Espresso          30

In [140]:
# Multiple ways to select columns
# coffee['Coffee Type']           # Single column (Series)
coffee[['Day', 'Units Sold']]       # Multiple columns (DataFrame)
# coffee.Day             # Single word columns only

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [68]:
# Set single value
coffee.loc[0] = 0  # Set value at row index 0, column 'Units Sold' (25 to 10)
print(coffee.loc[0:1])

      Day Coffee Type  Units Sold
0       0           0           0
1  Monday       Latte         150

In [78]:
# Set multiple values in one row
coffee.loc[0, ["Day","Coffee Type","Units Sold"]] = ["Sunday","Latte",300]
coffee.head()

         Day Coffee Type  Units Sold
0     Sunday       Latte         300
1     Monday    Espresso         250
2    Tuesday  Cappuccino         200
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [77]:
#set multiple values in multiple rows
coffee.loc[0:2, ["Day","Coffee Type","Units Sold"]] = [
    ["Sunday","Latte",300],
    ["Monday","Espresso",250],
    ["Tuesday","Cappuccino",200]
]
coffee.head()

         Day Coffee Type  Units Sold
0     Sunday       Latte         300
1     Monday    Espresso         250
2    Tuesday  Cappuccino         200
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [76]:
coffee=coffee.drop("Unit Sold", axis=1)
coffee

          Day Coffee Type  Units Sold
0      Sunday       Latte         300
1      Monday    Espresso         250
2     Tuesday  Cappuccino         200
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [86]:
#sort values
coffee.sort_values("Units Sold")
coffee.sort_values("Units Sold", ascending=False)
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0,0])

          Day Coffee Type  Units Sold
0      Sunday       Latte         300
1      Monday    Espresso         250
2     Tuesday  Cappuccino         200
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
5   Wednesday       Latte          25
3     Tuesday       Latte          20

In [9]:
#parquet file
parquet=pd.read_parquet("data\\results.parquet")
parquet.tail()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,None,26.0,False,None
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,None,28.0,False,None
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,None
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,None,NaN,False,None
308407,2022.0,Winter,None,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,None,None,24.0,False,None

In [10]:
#Excel file
excel=pd.read_excel("data\\olympics-data.xlsx")
excel.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [12]:
#feather file
feather=pd.read_feather("data\\results.feather")
feather.tail()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,None,26.0,False,None
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,None,28.0,False,None
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,None
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,None,NaN,False,None
308407,2022.0,Winter,None,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,None,None,24.0,False,None

## Filtering Data

### Basic Filtering

In [2]:
import pandas as pd
df = pd.read_csv('./data/bios.csv')
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [ ]:
df.loc[df["height_cm"] > 220]

df.loc[df["height_cm"] > 220,["name","height_cm","NOC"]]

height_210 = df.loc[
    (df["height_cm"] > 210) & (df["NOC"] == "United States"),
    ["name", "height_cm"]
]
height_210

                      name  height_cm
5681          Walt Bellamy      211.0
5781        Tommy Burleson      223.0
5894            Mel Counts      213.0
6059         Patrick Ewing      213.0
6106       Marc Freiberger      211.0
6281        Darrall Imhoff      211.0
6379            Joe Kleine      211.0
6393            Jon Koncak      213.0
6432           Bob Kurland      213.0
6442    Christian Laettner      211.0
6615          Tom McMillen      212.0
6722      Shaquille O'Neal      216.0
6735       Hakeem Olajuwon      213.0
6937        David Robinson      216.0
107419          Tim Duncan      213.0
112366       Dwight Howard      211.0
123850      Tyson Chandler      216.0
133332      DeAndre Jordan      211.0
143712        JaVale McGee      213.0

In [135]:
# Simple conditions
tall_athletes = df[df['height_cm'] > 200]
IND_athletes = df[df['born_country'] == 'IND']
IND_athletes

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
80,81,George Caridia,1869-02-20,Kolkata (Calcutta),West Bengal,IND,Great Britain,NaN,NaN,1937-04-21
101,102,Algernon Kingscote,1888-02-03,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1964-12-21
270,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01
273,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN
274,275,Anand Amritraj,1952-03-20,Chennai (Madras),Tamil Nadu,IND,India,185.0,77.0,NaN
...,...,...,...,...,...,...,...,...,...,...
140286,143790,Bajrang Punia,1994-02-26,Khudan,Haryana,IND,India,NaN,NaN,NaN
140287,143791,Deepak Punia,1999-05-19,Jhajjar,Haryana,IND,India,NaN,NaN,NaN
143996,147660,Sumit Nagal,1997-08-16,Jhajjar,Haryana,IND,India,NaN,NaN,NaN
144114,147784,Diksha Dagar,2000-12-14,Jhajjar,Haryana,IND,India,174.0,NaN,NaN
144757,148458,Arif Khan,1990-03-09,Gulmarg,Jammu and Kashmir,IND,India,NaN,NaN,NaN

In [155]:
df[df["name"].str.contains("silva", case=False)] # it gives all names with gowda or Gowda

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2466,2477,Fernando Silva,1972-12-17,Peniche,Distrito de Leiria,POR,Portugal,174.0,62.0,NaN
4056,4070,Silvano Bertini,1940-03-27,Lastra a Signa,Firenze,ITA,Italy,170.0,67.0,2021-06-27
4670,4687,Hermes Silva,1950-10-14,Siuna,Atlántico Norte,NCA,Nicaragua,157.0,50.0,NaN
4671,4688,René Silva,1954-11-27,León,León,NCA,Nicaragua,160.0,54.0,1978-06-03
4854,4872,Garth Da Silva,1973-12-28,Wellington,Wellington,NZL,New Zealand,183.0,91.0,NaN
...,...,...,...,...,...,...,...,...,...,...
137988,141372,Myriam Da Silva,1984-04-15,Chambly,Québec,CAN,Canada,NaN,NaN,NaN
140567,144079,Silvana Stanco,1993-01-06,Zürich,Zürich,SUI,Italy,161.0,NaN,NaN
142440,146048,Rui Silva,1993-04-28,Guimarães,Distrito de Braga,POR,Portugal,186.0,87.0,NaN
143026,146658,Silvan Wicki,1995-02-13,NaN,NaN,NaN,Switzerland,NaN,NaN,NaN
143195,146831,José Da Silva Viegas,2003-08-24,NaN,NaN,NaN,Timor-Leste,NaN,NaN,NaN

### Multiple Conditions

In [ ]:
# Use parentheses and & (and) or | (or)
filtered = df[(df['height_cm'] > 200) & (df['born_country'] == 'USA')]
filtered = df[(df['born_city'].str.contains("Bengaluru")) & (df['died_date'] != "Nan")]
filtered

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
101,102,Algernon Kingscote,1888-02-03,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1964-12-21
18639,18767,Charles Foulkes,1875-02-01,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1969-05-06
18744,18872,John Taylor,1928-03-18,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,2015-03-09
19025,19158,Rajendra Christy,1938-07-01,Bengaluru (Bangalore),Karnataka,IND,India,165.0,58.0,1992-12-22
19031,19164,Chinnadorai Desamuthu,1932-10-26,Bengaluru (Bangalore),Karnataka,IND,India,NaN,NaN,2017-01-01
19058,19192,Jude Sebastian,1965-01-26,Bengaluru (Bangalore),Karnataka,IND,India,162.0,62.0,NaN
25610,25802,S. A. Basheer,1924-01-01,Bengaluru (Bangalore),Karnataka,IND,India,NaN,NaN,1987-01-01
25618,25810,Mariappa Kempaiah,1933-02-10,Bengaluru (Bangalore),Karnataka,IND,India,165.0,62.0,2008-07-02
25637,25829,Mohammad Sattar,1925-01-01,Bengaluru (Bangalore),Karnataka,IND,India,NaN,NaN,2011-04-23
25643,25835,P. Venkatesh,1926-01-01,Bengaluru (Bangalore),Karnataka,IND,India,NaN,NaN,1977-06-01
92783,93528,Nisha Millet,1982-03-20,Bengaluru (Bangalore),Karnataka,IND,India,164.0,58.0,NaN
102809,103769,Shikha Tandon,1985-01-20,Bengaluru (Bangalore),Karnataka,IND,India,166.0,60.0,NaN
111590,112832,Anup Sridhar,1983-04-11,Bengaluru (Bangalore),Karnataka,IND,India,189.0,83.0,NaN
118985,120764,Gagan Ullalmath,1992-01-08,Bengaluru (Bangalore),Karnataka,IND,India,NaN,NaN,NaN
121851,123874,Rohan Bopanna,1980-03-04,Bengaluru (Bangalore),Karnataka,IND,India,190.0,87.0,NaN
122967,125117,Ashwini Ponnappa,1989-09-18,Bengaluru (Bangalore),Karnataka,IND,India,165.0,59.0,NaN
128047,130551,Aditi Ashok,1998-03-29,Bengaluru (Bangalore),Karnataka,IND,India,173.0,57.0,NaN
131638,134454,Prakash Nanjappa,1976-02-29,Bengaluru (Bangalore),Karnataka,IND,India,175.0,85.0,NaN

In [15]:
res = df[(df["weight_kg"] > 150) & (df["born_country"].str.contains("CH", case=False) | df["born_country"].str.contains("Usa", case=False))]
res

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
56584,56987,Thomas Ingalsbe,1969-11-16,Marietta,Georgia,USA,United States,195.0,152.0,NaN
60344,60777,Chris Taylor,1950-06-13,Dowagiac,Michigan,USA,United States,196.0,182.0,1979-06-30
113220,114511,Christian Cantwell,1980-09-30,Jefferson City,Missouri,USA,United States,193.0,154.0,NaN
124453,126756,Holley Mangold,1989-12-22,Kettering,Ohio,USA,United States,173.0,155.0,NaN
133317,136256,Mason Finley,1990-10-07,Kansas City,Missouri,USA,United States,203.0,158.0,NaN

##

### String Operations

In [17]:
# String methods with .str accessor
names_with_keith = df[df['name'].str.contains('Keith', case=False)]
starts_with_a = df[df['name'].str.startswith('A')]
ends_with_son = df[df['name'].str.endswith('son')]
ends_with_son

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
37,38,Helen Aitchison,1881-12-06,Sunderland,England,GBR,Great Britain,NaN,NaN,1947-05-26
92,93,Anne Gibson,1968-10-26,Dumfries,Scotland,GBR,Great Britain,173.0,70.0,NaN
113,114,Julian Robertson,1969-10-09,Peterborough,England,GBR,Great Britain,182.0,73.0,NaN
120,121,Chris Wilkinson,1970-01-05,Southampton,England,GBR,Great Britain,180.0,72.0,NaN
373,374,Don Jackson,1932-10-25,Lindsay,Ontario,CAN,Canada,178.0,NaN,2009-01-26
...,...,...,...,...,...,...,...,...,...,...
145419,149142,Jake Sanderson,2002-07-08,Whitefish,Montana,USA,United States,NaN,NaN,NaN
145424,149147,Jonathan Gustafson,1997-03-05,Massena,New York,USA,United States,NaN,NaN,NaN
145441,149164,Casey Dawson,2000-08-02,Park City,Utah,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145461,149188,Kent Johnson,2002-10-18,Port Moody,British Columbia,CAN,Canada,185.0,75.0,NaN

### Advanced String Filtering with Regex

In [ ]:
# Regular expressions for complex patterns
vowel_cities = df[df['born_city'].str.contains(r'^[AEIOU]', case=False, na=False)]  # Starts with vowel na= False because some values are NaN. na is used to ignore NaN values
double_letters = df[df['name'].str.contains(r'(.)\1', na=False)]  # Consecutive same letters
hyphenated_names = df[df['name'].str.contains(r'[-\']', na=False)]  # Contains hyphen or apostrophe
vowel_cities

C:\Users\CHANDAN\AppData\Local\Temp\ipykernel_19960\4096924551.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  double_letters = df[df['name'].str.contains(r'(.)\1', na=False)]  # Consecutive same letters

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
10,11,"Élie, Comte de Lastours",1874-08-12,Orgeval,Yvelines,FRA,France,NaN,NaN,1932-11-18
17,18,Jean-Philippe Gatien,1968-10-16,Alès,Gard,FRA,France,178.0,73.0,NaN
35,36,Étienne Thobois,1967-09-20,Amiens,Somme,FRA,France,186.0,78.0,NaN
40,41,Julie Bradbury,1967-02-12,Oxford,England,GBR,Great Britain,175.0,64.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145395,149118,Abbey Murphy,2002-04-14,Evergreen Park,Illinois,USA,United States,NaN,NaN,NaN
145398,149121,Grace Zumwinkle,1999-04-23,Excelsior,Minnesota,USA,United States,NaN,NaN,NaN
145405,149128,Brian Cooper,1993-11-01,Anchorage,Alaska,USA,United States,NaN,NaN,NaN
145418,149141,Nick Perbix,1998-06-15,Elk River,Minnesota,USA,United States,NaN,NaN,NaN
145427,149150,Jared Shumate,1999-03-06,Atlanta,Georgia,USA,United States,NaN,NaN,NaN

### Query Method

In [31]:
# Alternative filtering syntax
# df.query("weight_kg <50 & height_cm > 180")
df[(df["weight_kg"] < 50) & (df["height_cm"] >180) ]
# df.query("born_city == 'Seattle'")

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
7838,7879,Jannie Gibson,1941-05-15,Bulawayo,Bulawayo,ZIM,Zimbabwe,186.0,48.0,NaN
23502,23684,Bob Cottingham,1966-04-16,Orange,New Jersey,USA,United States,183.0,48.0,NaN

## Adding and Removing Columns

### Adding Simple Columns

In [10]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [11]:
# Add constant value
coffee['price'] = 4.99
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [12]:
import numpy as np
coffee["new_price"] = np.where(coffee["Coffee Type"] == "Latte", 5.99, 3.99)
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [14]:
coffee.drop("price", axis=1, inplace=True)
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [16]:
# Add calculated column
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso          25       3.99    99.75
1      Monday       Latte          15       5.99    89.85
2     Tuesday    Espresso          30       3.99   119.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       3.99   139.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       3.99   159.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       3.99   179.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       3.99   179.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       3.99   179.55
13     Sunday       Latte          35       5.99   209.65

In [17]:
coffee.rename(columns={"new_price": "Price", "Units Sold": "Units_Sold"}, inplace=True)
coffee

          Day Coffee Type  Units_Sold  Price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [18]:
coffee

          Day Coffee Type  Units_Sold  Price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [19]:
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [24]:
# Multiple conditions
df['size_category'] = np.where(df['height_cm'] < 165, 'Short',
                      np.where(df['height_cm'] < 185, 'Average', 'Tall'))

In [26]:
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,size_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [28]:
df["weight_class"] = np.where(df["weight_kg"] <60, "Fly weight",
                              np.where(df["weight_kg"] < 80, "light weight", "Heavy weight"))
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,size_category,weight_class
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,light weight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,light weight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,light weight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight

### Removing Columns

In [32]:
new_df=df.copy()
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [57]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,size_category,weight_class
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,light weight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,light weight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,light weight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight

In [58]:
new_df.drop("weight_class", axis=1, inplace=True)

In [49]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,size_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [59]:
new_df.drop(columns=["size_category"], inplace=True)

In [61]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [62]:

# Alternative: select only wanted columns
new_df[['name', 'NOC']]

                         name        NOC
0       Jean-François Blanchy     France
1              Arnaud Boetsch     France
2                Jean Borotra     France
3             Jacques Brugnon     France
4                Albert Canet     France
...                       ...        ...
145495      Polina Luchnikova        ROC
145496    Valeriya Merkusheva        ROC
145497        Yuliya Smirnova        ROC
145498         André Foussard     France
145499          Bill Phillips  Australia

[145500 rows x 2 columns]

### Renaming columns

In [63]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [66]:
new_df.rename(columns={"born_country":"contry_code"}, inplace=True)
new_df.head()

,athlete_id,name,born_date,born_city,born_region,contry_code,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

## Merging and Concatenating

### Merging DataFrames

In [6]:
nocs=pd.read_csv('data/noc_regions.csv')

In [69]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [70]:
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,size_category,weight_class
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,light weight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,light weight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,light weight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight

In [77]:
pd.merge(df,nocs,  left_on="born_country", right_on="NOC", how="inner")

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,size_category,weight_class,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,light weight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,light weight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,light weight,FRA,France,NaN
4,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,Average,light weight,FRA,France,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110634,121614,Aicha Fall,1993-05-06,Nouakchott,Nouakchott,MTN,Mauritania,160.0,46.0,NaN,Short,Fly weight,MTN,Mauritania,NaN
110635,121615,Jidou El-Moctar,1985-07-08,Nouakchott,Nouakchott,MTN,Mauritania,171.0,72.0,NaN,Average,light weight,MTN,Mauritania,NaN
110636,124002,Helema Williams,1991-10-11,Tauhunu,Manihiki,COK,Cook Islands,168.0,79.0,NaN,Average,light weight,COK,Cook Islands,NaN
110637,126960,J'maal Alexander,1993-10-26,Tortola,British Virgin Islands,IVB,British Virgin Islands,178.0,64.0,NaN,Average,light weight,IVB,"Virgin Islands, British",NaN
110638,127967,Peter Crook,1993-01-09,Tortola,British Virgin Islands,IVB,British Virgin Islands,186.0,75.0,NaN,Tall,light weight,IVB,"Virgin Islands, British",NaN

### Concatenating DataFrames

In [12]:
IND=df[df["born_country"]=="IND"]
IVB=df[df["born_country"]=="IVB"]
combined=pd.concat([IND,IVB], ignore_index=True)
combined

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,81,George Caridia,1869-02-20,Kolkata (Calcutta),West Bengal,IND,Great Britain,NaN,NaN,1937-04-21
1,102,Algernon Kingscote,1888-02-03,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1964-12-21
2,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01
3,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN
4,275,Anand Amritraj,1952-03-20,Chennai (Madras),Tamil Nadu,IND,India,185.0,77.0,NaN
...,...,...,...,...,...,...,...,...,...,...
533,147660,Sumit Nagal,1997-08-16,Jhajjar,Haryana,IND,India,NaN,NaN,NaN
534,147784,Diksha Dagar,2000-12-14,Jhajjar,Haryana,IND,India,174.0,NaN,NaN
535,148458,Arif Khan,1990-03-09,Gulmarg,Jammu and Kashmir,IND,India,NaN,NaN,NaN
536,126960,J'maal Alexander,1993-10-26,Tortola,British Virgin Islands,IVB,British Virgin Islands,178.0,64.0,NaN
537,127967,Peter Crook,1993-01-09,Tortola,British Virgin Islands,IVB,British Virgin Islands,186.0,75.0,NaN

## Handling Null Values

### Identifying Null Values

In [29]:
# Check for nulls
df.isnull().sum()           # Count nulls per column
# df.info()                   # Shows non-null count
# df[df['born_date'].isnull()]  # Rows with nulls in specific column

athlete_id           0
name                 0
born_date         1807
born_city        34592
born_region      34592
born_country     34592
NOC                  1
height_cm        38849
weight_kg        43430
died_date       111560
dtype: int64

In [77]:
df[df["born_date"].isnull()]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
12,13,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
13,14,Étienne Durand,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
27,28,"Guy, Baron Lejeune",NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
28,29,Albert Lippmann,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
108,109,Arthur Norris,NaN,NaN,NaN,NaN,Great Britain,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
126484,128839,Werner Fehr,NaN,NaN,NaN,NaN,Switzerland,NaN,NaN,1943-09-08
135275,138438,Aleko Mulos,NaN,NaN,NaN,NaN,Türkiye,NaN,NaN,NaN
135280,138443,Louis Léstienne,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
144129,147802,René Van Damme,NaN,NaN,NaN,NaN,Belgium,NaN,NaN,NaN
144132,147805,Raphael de Ligne,NaN,NaN,NaN,NaN,Belgium,NaN,NaN,NaN

### Filling Null Values

In [33]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [40]:
# Fill with constant
new_df['height_cm'].fillna(0,  inplace=True)
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,0.0,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,0.0,NaN,1930-07-25

In [41]:
# Fill with mean
weight=new_df['weight_kg'].fillna(new_df['weight_kg'].mean())
weight

0         71.890996
1         76.000000
2         76.000000
3         64.000000
4         71.890996
            ...
145495    61.000000
145496    65.000000
145497    55.000000
145498    71.890996
145499    71.890996
Name: weight_kg, Length: 145500, dtype: float64

In [46]:
#replacing 0 in height_cm back to NaN
import numpy as np
new_df["height_cm"].replace(0,np.nan, inplace=True)
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:

# Forward fill (use previous value)
new_df['height_cm'].fillna(method='ffill', inplace=True)
new_df.head()

C:\Users\CHANDAN\AppData\Local\Temp\ipykernel_22792\224024514.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df['height_cm'].fillna(method='ffill', inplace=True)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,168.0,NaN,1930-07-25

In [51]:
# Interpolate (estimate based on neighbors)
new_df['weight_kg'].interpolate(inplace=True)
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,168.0,67.0,1930-07-25

### Filling Null Values

In [63]:
new_df=df.copy()
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [64]:
# Drop rows with any null values
res=new_df.dropna()
res

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
107,108,Anders Nielsen,1967-02-24,Cape Town,Western Cape,RSA,Great Britain,173.0,70.0,2010-07-29
258,259,Tonny Maringgi,1959-06-10,Kendari,Sulawesi Tenggara,INA,Indonesia,167.0,65.0,2019-09-15
300,301,Jackson Fear,1978-01-13,Sydney,New South Wales,AUS,Australia,178.0,125.0,2006-07-21
...,...,...,...,...,...,...,...,...,...,...
135272,138435,Art Child,1916-09-15,West Ham,England,GBR,Great Britain,180.0,71.0,1996-06-30
135277,138440,Toyoko Yoshino,1920-02-12,Abashiri,Hokkaido,JPN,Japan,159.0,54.0,2015-01-24
135283,138446,Jacques Demaré,1900-09-01,Vincennes,Val-de-Marne,FRA,France,185.0,78.0,1935-12-09
136653,139884,Johanna Bassani,2002-04-25,Vöcklabruck,Oberösterreich,AUT,Austria,163.0,54.0,2020-05-05
141190,144729,Naonobu Fujii,1992-01-05,Ishinomaki,Miyagi,JPN,Japan,183.0,80.0,2023-03-10

In [65]:
# Drop rows with nulls in specific columns
res=new_df.dropna(subset=['weight_kg'])
res

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145473,149200,Toms Andersons,1993-11-25,Rīga,Rīga,LAT,Latvia,185.0,86.0,NaN
145474,149201,Nadine Hofstetter,1994-10-21,Romoos,Luzern,SUI,Switzerland,164.0,68.0,NaN
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN

In [67]:
# Drop columns with too many nulls
res=new_df.dropna(axis=1, thresh=100)  # Keep columns with at least 100 non-null values
res

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

## Data Aggregation

### Value Counts

In [71]:
# Count unique values
new_df[['name']].value_counts().head(10)

name
Ivan Ivanov            13
Luis López              9
José González           9
José Pérez              8
Juan Martínez           7
José Martínez           7
José García             7
Luis Martínez           7
Luis González           7
Francisco Rodríguez     7
Name: count, dtype: int64

In [81]:
df["born_region"].value_counts()

born_region
England            4824
Ontario            1710
California         1634
Budapest           1447
New South Wales    1120
                   ...
Chimborazo            1
Taraclia              1
Gjirokastër           1
Santa Rosa            1
Vĩnh Long             1
Name: count, Length: 2554, dtype: int64

In [ ]:
# Count unique values with condition
df[df["born_country"]=="IND"]["born_region"].value_counts()

born_region
Punjab                                 94
Maharashtra                            56
West Bengal                            49
Haryana                                43
Uttar Pradesh                          42
Tamil Nadu                             34
Karnataka                              32
National Capital Territory of Delhi    32
Kerala                                 26
Andhra Pradesh                         23
Madhya Pradesh                         22
Rajasthan                              14
Manipur                                10
Himachal Pradesh                       10
Gujarat                                 9
Bihar                                   6
Jharkhand                               5
Assam                                   5
Jammu and Kashmir                       5
Uttarakhand                             4
Tripura                                 3
Chandigarh                              2
Goa                                     2
Chhattisgarh                            2
Nagaland                                2
Sikkim                                  1
Mizoram                                 1
Puducherry                              1
Orissa                                  1
Name: count, dtype: int64

In [86]:
#counting which country has most athletes greater than 200 cm
df[df["height_cm"]> 200]["born_country"].value_counts()

born_country
USA    152
GER     90
RUS     65
BRA     47
POL     46
      ...
ZIM      1
COD      1
URU      1
TJK      1
NIG      1
Name: count, Length: 75, dtype: int64

### GroupBy Operations

In [ ]:
# this will give max height of each country from 95th index to last index
grouped = new_df.groupby('born_country')["height_cm"].max().iloc[95:] 
grouped

born_country
HON       188.0
HUN       209.0
Havel     179.0
INA       204.0
IND       200.0
          ...
VIN       187.0
Vienna    183.0
YEM       175.0
ZAM       191.0
ZIM       205.0
Name: height_cm, Length: 141, dtype: float64

In [ ]:
# Multiple aggregations
#this will give sum of height and mean of weight for each country
agg_results = df.groupby('born_country').agg({
    'height_cm': 'sum',
    'weight_kg': 'mean',
}) 

agg_results

              height_cm  weight_kg
born_country
AFG              4090.0  68.521739
AGU               186.0  78.000000
ALB              6637.0  76.027778
ALG             24885.0  68.043796
AND              5335.0  67.451613
...                 ...        ...
VIN               906.0  70.600000
Vienna            513.0  70.666667
YEM               676.0  55.250000
ZAM              9006.0  68.400000
ZIM             17354.0  67.061224

[236 rows x 2 columns]

In [ ]:
# Multiple groupby columns
# this will give sum of height for each country and region
df.groupby(['born_country', 'born_region'])['height_cm'].sum()

born_country  born_region
AFG           Kabul                 3925.0
              Kandahar               165.0
AGU           Anguilla               186.0
ALB           Dibër                  159.0
              Durrës                 345.0
                                     ...
ZIM           Mashonaland East       373.0
              Mashonaland West       531.0
              Masvingo               343.0
              Matabeleland South     160.0
              Midlands               870.0
Name: height_cm, Length: 2616, dtype: float64

In [111]:
dead_by_country = df.groupby('born_country')['died_date'].count()
dead_by_country.sort_values(ascending=False).head(10)

born_country
USA    3036
GBR    2443
FRA    2115
GER    1463
ITA    1463
SWE    1313
HUN    1060
NED     964
CAN     949
NOR     871
Name: died_date, dtype: int64

### Pivot Tables

In [147]:
coffee.head()

         Day Coffee Type  Units_Sold  Price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [150]:
# Create pivot table
'''pivot is used to summarize and aggregate data in a tabular format, making it easier to analyze and interpret.'''

# this will give revenue of each coffee type for each day
pivot = coffee.pivot(columns='Coffee Type', index='Day', values='revenue') 
coffee.head()
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   89.85
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75

In [157]:
pivot = df.pivot_table(
    index="born_country",
    columns="NOC",
    values="height_cm",
    aggfunc="mean"
)
pivot

NOC,Afghanistan,Albania,Albania Australia,Albania Bulgaria,Albania Greece,Albania Kosovo,Albania United States,Algeria,Algeria France,American Samoa,...,Uzbekistan,Vanuatu,Venezuela,Vietnam,West Germany,West Indies Federation,Yemen,Yugoslavia,Zambia,Zimbabwe
born_country,,,,,,,,,,,,,,,,,,,,,
AFG,170.130435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ALB,NaN,176.32,166.0,189.0,165.0,NaN,163.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ALG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176.788991,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vienna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,167.666667,NaN,NaN,NaN
ZAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171.809524,173.666667
ZIM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.000000,173.320513

## Advanced Functionality

### Shift Operations

In [42]:
# Compare with previous period

 #shift will shift values down by 2 rows
coffee['yesterday_revenue'] = coffee['revenue'].shift(2)
coffee

,Day,Coffee Type,Units_Sold,Price,revenue,most revenue,yesterday_revenue
0,Monday,Espresso,25,3.99,99.75,13.0,NaN
1,Monday,Latte,15,5.99,89.85,14.0,NaN
2,Tuesday,Espresso,30,3.99,119.70,12.0,99.75
3,Tuesday,Latte,20,5.99,119.80,11.0,89.85
4,Wednesday,Espresso,35,3.99,139.65,10.0,119.70
5,Wednesday,Latte,25,5.99,149.75,9.0,119.80
6,Thursday,Espresso,40,3.99,159.60,8.0,139.65
7,Thursday,Latte,30,5.99,179.70,4.0,149.75
8,Friday,Espresso,45,3.99,179.55,6.0,159.60
9,Friday,Latte,35,5.99,209.65,2.0,179.70
10,Saturday,Espresso,45,3.99,179.55,6.0,179.55
11,Saturday,Latte,35,5.99,209.65,2.0,209.65
12,Sunday,Espresso,45,3.99,179.55,6.0,179.55
13,Sunday,Latte,35,5.99,209.65,2.0,209.65

In [164]:
coffee['change'] = coffee['revenue'] - coffee['yesterday_revenue']
coffee

,Day,Coffee Type,Units_Sold,Price,revenue,yesterday_revenue,change
0,Monday,Espresso,25,3.99,99.75,NaN,NaN
1,Monday,Latte,15,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,99.75,19.95
3,Tuesday,Latte,20,5.99,119.80,89.85,29.95
4,Wednesday,Espresso,35,3.99,139.65,119.70,19.95
5,Wednesday,Latte,25,5.99,149.75,119.80,29.95
6,Thursday,Espresso,40,3.99,159.60,139.65,19.95
7,Thursday,Latte,30,5.99,179.70,149.75,29.95
8,Friday,Espresso,45,3.99,179.55,159.60,19.95
9,Friday,Latte,35,5.99,209.65,179.70,29.95
10,Saturday,Espresso,45,3.99,179.55,179.55,0.00
11,Saturday,Latte,35,5.99,209.65,209.65,0.00
12,Sunday,Espresso,45,3.99,179.55,179.55,0.00
13,Sunday,Latte,35,5.99,209.65,209.65,0.00

In [166]:
coffee['percent_change'] = ((coffee['revenue'] / coffee['yesterday_revenue'] - 1) * 100 ).round(1)
coffee

,Day,Coffee Type,Units_Sold,Price,revenue,yesterday_revenue,change,percent_change
0,Monday,Espresso,25,3.99,99.75,NaN,NaN,NaN
1,Monday,Latte,15,5.99,89.85,NaN,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,99.75,19.95,20.0
3,Tuesday,Latte,20,5.99,119.80,89.85,29.95,33.3
4,Wednesday,Espresso,35,3.99,139.65,119.70,19.95,16.7
5,Wednesday,Latte,25,5.99,149.75,119.80,29.95,25.0
6,Thursday,Espresso,40,3.99,159.60,139.65,19.95,14.3
7,Thursday,Latte,30,5.99,179.70,149.75,29.95,20.0
8,Friday,Espresso,45,3.99,179.55,159.60,19.95,12.5
9,Friday,Latte,35,5.99,209.65,179.70,29.95,16.7
10,Saturday,Espresso,45,3.99,179.55,179.55,0.00,0.0
11,Saturday,Latte,35,5.99,209.65,209.65,0.00,0.0
12,Sunday,Espresso,45,3.99,179.55,179.55,0.00,0.0
13,Sunday,Latte,35,5.99,209.65,209.65,0.00,0.0

### Ranking

In [189]:
coffee = coffee.drop(coffee.columns[-5:], axis=1)

coffee

          Day Coffee Type  Units_Sold  Price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [22]:
# Rank values (1 = highest by default)
coffee['most revenue'] = coffee['revenue'].rank(ascending=False)
coffee

          Day Coffee Type  Units_Sold  Price  revenue  most revenue
0      Monday    Espresso          25   3.99    99.75          13.0
1      Monday       Latte          15   5.99    89.85          14.0
2     Tuesday    Espresso          30   3.99   119.70          12.0
3     Tuesday       Latte          20   5.99   119.80          11.0
4   Wednesday    Espresso          35   3.99   139.65          10.0
5   Wednesday       Latte          25   5.99   149.75           9.0
6    Thursday    Espresso          40   3.99   159.60           8.0
7    Thursday       Latte          30   5.99   179.70           4.0
8      Friday    Espresso          45   3.99   179.55           6.0
9      Friday       Latte          35   5.99   209.65           2.0
10   Saturday    Espresso          45   3.99   179.55           6.0
11   Saturday       Latte          35   5.99   209.65           2.0
12     Sunday    Espresso          45   3.99   179.55           6.0
13     Sunday       Latte          35   5.99   209.65           2.0

In [ ]:
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [31]:
avg_height = df.groupby("born_country")["height_cm"].mean()
avg_height

born_country
AFG       170.416667
AGU       186.000000
ALB       174.657895
ALG       176.489362
AND       172.096774
             ...
VIN       181.200000
Vienna    171.000000
YEM       169.000000
ZAM       173.192308
ZIM       173.540000
Name: height_cm, Length: 236, dtype: float64

In [41]:
ranked = avg_height.rank(ascending=False)  # Higher height = Rank 1
result = pd.DataFrame({
    "avg_height": avg_height,
    "rank": ranked
}).sort_values("rank")

ranked
result

              avg_height  rank
born_country
Milde         196.500000   1.0
Prignitz      194.000000   2.0
GIB           191.000000   3.0
AGU           186.000000   4.0
MNE           185.982456   5.0
...                  ...   ...
Luppe                NaN   NaN
Munich               NaN   NaN
NFI                  NaN   NaN
SEY                  NaN   NaN
Spreewald            NaN   NaN

[236 rows x 2 columns]

### Rolling Windows

In [46]:
# 3-day rolling average
res=coffee['3day_avg_revenue'] = coffee['revenue'].rolling(window=3).mean()
coffee

,Day,Coffee Type,Units_Sold,Price,revenue,most revenue,yesterday_revenue,3day_avg_revenue
0,Monday,Espresso,25,3.99,99.75,13.0,NaN,NaN
1,Monday,Latte,15,5.99,89.85,14.0,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,12.0,99.75,103.100000
3,Tuesday,Latte,20,5.99,119.80,11.0,89.85,109.783333
4,Wednesday,Espresso,35,3.99,139.65,10.0,119.70,126.383333
5,Wednesday,Latte,25,5.99,149.75,9.0,119.80,136.400000
6,Thursday,Espresso,40,3.99,159.60,8.0,139.65,149.666667
7,Thursday,Latte,30,5.99,179.70,4.0,149.75,163.016667
8,Friday,Espresso,45,3.99,179.55,6.0,159.60,172.950000
9,Friday,Latte,35,5.99,209.65,2.0,179.70,189.633333
10,Saturday,Espresso,45,3.99,179.55,6.0,179.55,189.583333
11,Saturday,Latte,35,5.99,209.65,2.0,209.65,199.616667
12,Sunday,Espresso,45,3.99,179.55,6.0,179.55,189.583333
13,Sunday,Latte,35,5.99,209.65,2.0,209.65,199.616667

In [49]:
# Rolling sum
coffee['3day_total'] = coffee['revenue'].rolling(window=3).sum()
coffee

,Day,Coffee Type,Units_Sold,Price,revenue,most revenue,yesterday_revenue,3day_avg_revenue,3day_total
0,Monday,Espresso,25,3.99,99.75,13.0,NaN,NaN,NaN
1,Monday,Latte,15,5.99,89.85,14.0,NaN,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,12.0,99.75,103.100000,309.30
3,Tuesday,Latte,20,5.99,119.80,11.0,89.85,109.783333,329.35
4,Wednesday,Espresso,35,3.99,139.65,10.0,119.70,126.383333,379.15
5,Wednesday,Latte,25,5.99,149.75,9.0,119.80,136.400000,409.20
6,Thursday,Espresso,40,3.99,159.60,8.0,139.65,149.666667,449.00
7,Thursday,Latte,30,5.99,179.70,4.0,149.75,163.016667,489.05
8,Friday,Espresso,45,3.99,179.55,6.0,159.60,172.950000,518.85
9,Friday,Latte,35,5.99,209.65,2.0,179.70,189.633333,568.90
10,Saturday,Espresso,45,3.99,179.55,6.0,179.55,189.583333,568.75
11,Saturday,Latte,35,5.99,209.65,2.0,209.65,199.616667,598.85
12,Sunday,Espresso,45,3.99,179.55,6.0,179.55,189.583333,568.75
13,Sunday,Latte,35,5.99,209.65,2.0,209.65,199.616667,598.85

### Cumulative Operations

In [ ]:
# Running totals
coffee['cumulative_revenue'] = coffee['revenue'].cumsum()
coffee

,Day,Coffee Type,Units_Sold,Price,revenue,most revenue,yesterday_revenue,3day_avg_revenue,3day_total,cumulative_revenue
0,Monday,Espresso,25,3.99,99.75,13.0,NaN,NaN,NaN,99.75
1,Monday,Latte,15,5.99,89.85,14.0,NaN,NaN,NaN,189.60
2,Tuesday,Espresso,30,3.99,119.70,12.0,99.75,103.100000,309.30,309.30
3,Tuesday,Latte,20,5.99,119.80,11.0,89.85,109.783333,329.35,429.10
4,Wednesday,Espresso,35,3.99,139.65,10.0,119.70,126.383333,379.15,568.75
5,Wednesday,Latte,25,5.99,149.75,9.0,119.80,136.400000,409.20,718.50
6,Thursday,Espresso,40,3.99,159.60,8.0,139.65,149.666667,449.00,878.10
7,Thursday,Latte,30,5.99,179.70,4.0,149.75,163.016667,489.05,1057.80
8,Friday,Espresso,45,3.99,179.55,6.0,159.60,172.950000,518.85,1237.35
9,Friday,Latte,35,5.99,209.65,2.0,179.70,189.633333,568.90,1447.00
10,Saturday,Espresso,45,3.99,179.55,6.0,179.55,189.583333,568.75,1626.55
11,Saturday,Latte,35,5.99,209.65,2.0,209.65,199.616667,598.85,1836.20
12,Sunday,Espresso,45,3.99,179.55,6.0,179.55,189.583333,568.75,2015.75
13,Sunday,Latte,35,5.99,209.65,2.0,209.65,199.616667,598.85,2225.40

In [58]:
coffee['cumulative_count'] = coffee['Units_Sold'].cumsum()
coffee

,Day,Coffee Type,Units_Sold,Price,revenue,most revenue,yesterday_revenue,3day_avg_revenue,3day_total,cumulative_revenue,cumulative_count
0,Monday,Espresso,25,3.99,99.75,13.0,NaN,NaN,NaN,99.75,25
1,Monday,Latte,15,5.99,89.85,14.0,NaN,NaN,NaN,189.60,40
2,Tuesday,Espresso,30,3.99,119.70,12.0,99.75,103.100000,309.30,309.30,70
3,Tuesday,Latte,20,5.99,119.80,11.0,89.85,109.783333,329.35,429.10,90
4,Wednesday,Espresso,35,3.99,139.65,10.0,119.70,126.383333,379.15,568.75,125
5,Wednesday,Latte,25,5.99,149.75,9.0,119.80,136.400000,409.20,718.50,150
6,Thursday,Espresso,40,3.99,159.60,8.0,139.65,149.666667,449.00,878.10,190
7,Thursday,Latte,30,5.99,179.70,4.0,149.75,163.016667,489.05,1057.80,220
8,Friday,Espresso,45,3.99,179.55,6.0,159.60,172.950000,518.85,1237.35,265
9,Friday,Latte,35,5.99,209.65,2.0,179.70,189.633333,568.90,1447.00,300
10,Saturday,Espresso,45,3.99,179.55,6.0,179.55,189.583333,568.75,1626.55,345
11,Saturday,Latte,35,5.99,209.65,2.0,209.65,199.616667,598.85,1836.20,380
12,Sunday,Espresso,45,3.99,179.55,6.0,179.55,189.583333,568.75,2015.75,425
13,Sunday,Latte,35,5.99,209.65,2.0,209.65,199.616667,598.85,2225.40,460

In [56]:
pd.__version__

'2.1.3'